[tool.poetry]
name = "koda"
version = "0.1.0"
description = ""
authors = ["Keith Philpott"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
coverage = "6.0.2"
mypy = "0.910"
pytest = "6.2.5"
pytest-cov = "3.0.0"
openapi-spec-validator = "0.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
