[tool.poetry]
name = "koda"
version = "0.1.0"
description = ""
authors = ["Keith Philpott"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
coverage = "~5.5"
mypy = "~0.812"
pytest = "~6.2.3"
pytest-cov = "~2.11.1"
openapi-spec-validator = "~0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
